"""Safe DB Gateway — 3-step local setup:  init  ->  up  ->  paste MCP JSON.

  python setup.py init [--demo] [--role reader|editor|admin]
  python setup.py up

init writes .env (never overwrites without --force). up starts Postgres via
docker compose, waits for health, provisions roles/views/tables/RLS, and
prints the exact MCP JSON to paste into Claude Desktop. Stdlib only.
"""
import argparse
import json
import os
import secrets
import socket
import subprocess
import sys
import time

ROOT = os.path.abspath(os.path.dirname(__file__))
ENV_PATH = os.path.join(ROOT, ".env")
MCP_JSON_PATH = os.path.join(ROOT, "mcp-servers.json")


def _gen_secret(nbytes: int = 24) -> str:
    # urlsafe alphabet: no quotes/spaces -> safe in .env, URLs and SQL strings.
    return secrets.token_urlsafe(nbytes)


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        answer = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        answer = ""
    return answer or default


def _load_env_file() -> dict:
    values = {}
    if os.path.exists(ENV_PATH):
        with open(ENV_PATH, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    values[k.strip()] = v.strip()
    return values


def cmd_init(args) -> int:
    existing = _load_env_file()
    if existing and not args.force and not args.demo:
        print(f".env already exists at {ENV_PATH}. Re-run with --force to overwrite.")
        return 1

    demo = args.demo
    if demo:
        db_host, db_port, db_name = "127.0.0.1", "5433", "chinook"
        role = args.role or "reader"
        postgres_pw = _gen_secret()
    elif sys.stdin.isatty():
        print("Safe DB Gateway — init (empty = default).")
        use_demo = _ask("Use bundled demo DB via docker compose? (Y/n)", "Y")
        if use_demo.lower().startswith("n"):
            db_host = _ask("Postgres host", os.getenv("DB_HOST", "127.0.0.1"))
            db_port = _ask("Postgres port", os.getenv("DB_PORT", "5433"))
            db_name = _ask("Database name", os.getenv("DB_NAME", "chinook"))
        else:
            db_host, db_port, db_name = "127.0.0.1", "5433", "chinook"
        role = (args.role or _ask("Keycard for this deployment (reader/editor/admin)",
                                  "reader")).strip().lower()
        if role not in ("reader", "editor", "admin"):
            print(f"Unknown role '{role}', using reader.")
            role = "reader"
        postgres_pw = _ask("Postgres superuser password (blank = generate)",
                           "") or _gen_secret()
    else:
        db_host = os.getenv("DB_HOST", "127.0.0.1")
        db_port = os.getenv("DB_PORT", "5433")
        db_name = os.getenv("DB_NAME", "chinook")
        role = (args.role or os.getenv("GATEWAY_ROLE", "reader")).strip().lower()
        if role not in ("reader", "editor", "admin"):
            role = "reader"
        postgres_pw = os.getenv("POSTGRES_PASSWORD", "") or _gen_secret()

    operator_key = _gen_secret()
    role_passwords = {r: _gen_secret() for r in ("reader", "editor", "admin")}
    # Legacy service accounts keep working (circuit-breaker service identity).
    agent_ro_pw = _gen_secret()
    agent_rw_pw = _gen_secret()

    lines = [
        "# Generated by `python setup.py init`. Do not commit this file.",
        "DB_ENGINE=postgresql",
        f"DB_HOST={db_host}",
        f"DB_PORT={db_port}",
        f"DB_NAME={db_name}",
        f"POSTGRES_PASSWORD={postgres_pw}",
        "DB_SSLMODE=prefer",
        f"DATABASE_URL=postgresql://agent_ro:{agent_ro_pw}@{db_host}:{db_port}/{db_name}",
        f"DB_MUTATION_URL=postgresql://agent_rw:{agent_rw_pw}@{db_host}:{db_port}/{db_name}",
        f"DB_USER=agent_ro",
        f"DB_PASSWORD={agent_ro_pw}",
        f"DB_MUTATION_USER=agent_rw",
        f"DB_MUTATION_PASSWORD={agent_rw_pw}",
        f"GATEWAY_ROLE={role}",
        f"GATEWAY_READER_PASSWORD={role_passwords['reader']}",
        f"GATEWAY_EDITOR_PASSWORD={role_passwords['editor']}",
        f"GATEWAY_ADMIN_PASSWORD={role_passwords['admin']}",
        f"OPERATOR_APPROVAL_SECRET={operator_key}",
        "DB_MAX_ROWS=100",
        "DB_TIMEOUT_SECONDS=2.0",
        "DB_MAX_PAYLOAD_BYTES=524288",
        "",
    ]
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    # setup_roles.py authenticates as superuser with POSTGRES_PASSWORD.
    print(f"Wrote {ENV_PATH} (role={role}, fresh secrets generated).")
    print("Superuser password stored as POSTGRES_PASSWORD (compose + provisioning).")
    return 0


def _wait_for_postgres(host: str, port: int, timeout_s: int = 90) -> bool:
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        try:
            with socket.create_connection((host, int(port)), timeout=3):
                return True
        except OSError:
            time.sleep(2)
    return False


def cmd_up(args) -> int:
    if not os.path.exists(ENV_PATH):
        print("No .env found. Run `python setup.py init` first.")
        return 1

    env = _load_env_file()
    host = env.get("DB_HOST", "127.0.0.1")
    port = int(env.get("DB_PORT", "5433"))

    print("[1/3] Starting Postgres (docker compose)...", flush=True)
    if _wait_for_postgres(host, port, timeout_s=5):
        print(f"  Postgres already reachable at {host}:{port}; skipping compose + wait.")
    else:
        r = subprocess.run(["docker", "compose", "up", "-d", "db"], cwd=ROOT)
        if r.returncode != 0:
            print("docker compose failed. Is Docker running?")
            return r.returncode
        print("[2/3] Waiting for Postgres to accept connections...", flush=True)
        if not _wait_for_postgres(host, port):
            print(f"Timed out waiting for {host}:{port}. Check `docker compose logs db`.")
            return 1

    print("[3/3] Provisioning roles/views/tables (setup_roles.py)...", flush=True)
    setup_env = dict(os.environ)
    setup_env.update(env)
    # setup_roles.py reads POSTGRES_PASSWORD for the superuser connection.
    if "POSTGRES_PASSWORD" not in setup_env:
        setup_env["POSTGRES_PASSWORD"] = "postgres"
    r = subprocess.run([sys.executable, os.path.join(ROOT, "scripts", "setup_roles.py")],
                       cwd=ROOT, env=setup_env)
    if r.returncode != 0:
        print("Provisioning failed — see output above.")
        return r.returncode

    mcp_config = {
        "mcpServers": {
            "safe-db-gateway": {
                "command": sys.executable,
                "args": ["-m", "src.db_mcp.server"],
                "cwd": ROOT,
            }
        }
    }
    with open(MCP_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(mcp_config, f, indent=2)
    print(f"\nWrote {MCP_JSON_PATH}. Paste this into Claude Desktop config:")
    print(json.dumps(mcp_config, indent=2))
    print("\nDone. Gateway role for this deployment: "
          f"{env.get('GATEWAY_ROLE', 'reader')} (change via setup.py init --force or roles.yaml).")
    return 0


def main() -> int:
    # Secrets travel via .env / secret managers, never via CLI flags (they
    # leak into shell history, process lists, and CI logs). Refuse outright.
    for arg in sys.argv[1:]:
        lowered = arg.lower()
        if lowered.startswith(("--password", "--db-password", "--secret")) \
                or "://" in arg and "@" in arg \
                or lowered.startswith(("database_url=", "db_password=",
                                       "postgres_password=", "operator_approval_secret=")):
            print("Refused: pass secrets via .env or a secret manager, never as "
                  "command-line arguments (they leak into shell history and process lists).")
            return 2
    parser = argparse.ArgumentParser(description="Safe DB Gateway local setup.")
    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="Write .env (wizard or --demo).")
    p_init.add_argument("--demo", action="store_true",
                        help="Non-interactive demo defaults.")
    p_init.add_argument("--force", action="store_true",
                        help="Overwrite existing .env.")
    p_init.add_argument("--role", default="",
                        help="Keycard for this deployment: reader|editor|admin.")

    sub.add_parser("up", help="Start DB, provision, emit MCP JSON.")

    args = parser.parse_args()
    if args.command == "init":
        return cmd_init(args)
    return cmd_up(args)


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] in ("init", "up"):
        sys.exit(main())
    # Anything else (e.g. `setup.py egg_info` invoked by pip/setuptools
    # during `pip install .`): delegate to setuptools. All packaging
    # metadata lives in pyproject.toml.
    try:
        from setuptools import setup
    except ImportError:
        print("Unknown command. Use: python setup.py init|up "
              "(packaging commands run via `pip install .`, not setup.py directly).")
        sys.exit(2)
    setup()
